DEFAULT_TICKER = '^IXIC'
DEFAULT_LOOKBACK_YEARS = 7

TEST_SIZE = 0.2
RANDOM_STATE = 42
EARLY_STOPPING_PATIENCE = 15
MAX_EPOCHS = 150
BATCH_SIZE = 32

MODEL_OUTPUT_DIR = '../models'
VISUALIZATION_OUTPUT_DIR = '../visualizations'